# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main  # or any branch you want

pool:
  vmImage: 'ubuntu-latest'

variables:
  FEED_NAME: 'HelloFeed'         # Replace with your Azure Artifacts feed name
  PACKAGE_NAME: 'HelloWorldBin'  # Name for the uploaded binary package
  PACKAGE_VERSION: '1.0.0'       # Update version as needed

steps:
- checkout: none

- script: |
    git clone https://github.com/mayurjagtap15/HelloWorld.git
  displayName: 'Clone GitHub Repo'

- script: |
    cd HelloWorld
    javac HelloWorld.java
    mkdir -p ../output
    mv HelloWorld.class ../output/
  displayName: 'Compile Java Code'

- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: 'output'
    feedsToUse: 'internal'
    vstsFeed: '$(FEED_NAME)'
    packageName: '$(PACKAGE_NAME)'
    packageVersion: '$(PACKAGE_VERSION)'
  displayName: 'Publish to Azure Artifacts Feed'

